// Snapshot of the site content saved in Supabase (table `content`), taken on 2026-09-24.
// Used as the initial content so the site shows the real texts, contacts and photos
// immediately and even when the database is unreachable. Values from the DB override these.
export const CONTENT_DEFAULTS: Record<string, string> = {
  "browser_tab_title": "Raquel Neumann | Oficial",
  "business_name": "Raquel Neumann",
  "footer_brand_desc": "Tratamentos para disfunção erétil, ejaculação precoce, dores na relação, diminuição da libido, ausência de prazer, dificuldade em ter orgamos.",
  "footer_brand_subtitle": "Fisioterapia Pélvica & Terapias Sensoriais",
  "footer_contact_address": "Rua 700 n 489 sl 1203\nBalneário Camboriú/SC\nCep: 88330620",
  "footer_contact_phone": "47996097029",
  "footer_services_item1": "Femininos",
  "footer_services_item2": "Masculinos",
  "footer_services_item3": "Casais",
  "footer_services_item4": "Cursos de Tantra ",
  "footer_services_item5": "Curso de Pompoarismo",
  "footer_services_item6": "Experiências Sensoriais",
  "home_diferenciais_item3": "Atendimento para casais",
  "home_diferenciais_item6": "Cursos individuais ou em grupo",
  "home_dor_item4": "Ausência de orgasmo",
  "home_dor_item5": "Dores na relação",
  "home_dor_item6": "Diminuição da libido",
  "home_dor_title": "Você está enfrentando dificuldades na sua vida íntima?",
  "home_hero_btn1_href": "https://wa.me/5547996097029",
  "home_hero_btn1_label": "Agendar Atendimento",
  "home_hero_btn2_href": "https://wa.me/5547996097029",
  "home_hero_btn2_label": "Falar no WhatsApp",
  "home_hero_subtitle": "O prazer não começa na intimidade. Começa na forma como você vive, sente e se comunica com o próprio corpo. Meu trabalho é conduzir homens e mulheres nesse caminho de reconexão, saúde  íntima e prazer de viver.",
  "home_hero_title1": "Fisioterapia Pélvica & Terapias Sensorias",
  "home_hero_title1_color": "text-wine-900",
  "home_hero_title2": "com Raquel Neumann",
  "home_metodo_pilar1_desc": "Reconexão corporal e expansão da sensibilidade",
  "home_metodo_pilar3_desc": "Energia do prazer de viver através dos sentir.",
  "home_metodo_quote": "\"Quando você volta a sentir o próprio corpo, descobre que o verdadeiro prazer não está somente no sexo. Está na forma de viver.\"",
  "home_objecoes_item1": "Sente que perdeu a conexão com o próprio corpo.",
  "home_objecoes_item2": "Percebe que o estresse e a ansiedade têm afetado seu bem-estar.",
  "home_objecoes_item3": "Enfrenta dificuldades relacionadas à sexualidade ou ao prazer.",
  "home_objecoes_item4": "Busca uma relação mais saudável com seu corpo e suas emoções.",
  "home_objecoes_item5": "Deseja melhorar sua saúde íntima e qualidade de vida.",
  "home_objecoes_item6": "Quer fortalecer o assoalho pélvico e prevenir ou tratar disfunções.",
  "home_objecoes_subtitle": "Esse trabalho é indicado para quem:",
  "home_objecoes_title": "Isso é para você se:",
  "home_servicos_item1_desc": "Acompanhamento terapêutico para homens que enfrentam dificuldade de obter ou manter ereção, ejaculação precoce, anorgasmia, ansiedade de performance.",
  "home_servicos_item1_title": "Masculinos",
  "home_servicos_item2_desc": "Acompanhamento terapêutico para mulheres com queixas de ausência ou dificuldades em ter orgasmo, dores na relação, diminuição da libido, ausência de prazer.",
  "home_servicos_item2_title": "Femininos",
  "home_servicos_item3_desc": "Apaixone-se pelo prazer de sentir e dominar o seu próprio corpo.",
  "home_servicos_item3_title": "Cursos de Pompoarismo",
  "home_servicos_item4_desc": "Desenvolvimento da consciência corporal, expansão da sensibilidade e reconexão com o prazer.",
  "home_servicos_item5_desc": "Experiências terapêuticas que fortalecem a conexão, a comunicação, o toque e a intimidade, ajudando o casal a cultivar uma relação mais presente, leve e prazerosa. ",
  "home_servicos_item5_title": "Reconexão para Casais",
  "home_servicos_item6_desc": "Desperte os sentidos através de um momento único de autocuidado.",
  "home_servicos_item6_title": "Spa sensorial",
  "home_servicos_subtitle": "Raquel Neumann",
  "home_sobre_image": "https://shpbvncguqczyohymjjx.supabase.co/storage/v1/object/public/site-images/1uy373plego-1781453889545.jpg",
  "home_sobre_image_fit": "object-cover",
  "home_sobre_image_size": "scale-110",
  "home_sobre_p1": "Raquel Neumann é terapeuta especializada em fisioterapia pélvica e terapia sexual.",
  "home_sobre_p2": "Atua há 18 anos, auxiliando homens e mulheres a superarem queixas e bloqueios emocionais relacionados à sexualidade.\nTratamentos para: disfunção erétil, ejaculação precoce, perda urinária, ausência ou dificuldade de ter orgasmo, dores na relação, diminuição da libido., ou para quem quer aprimorar a sua vida sexual e se reconectar com o prazer.\n",
  "home_sobre_p3": "Sua forma de trabalhar une ciência, acolhimento e consciência, porque acredito que conhecimento técnico e sensibilidade caminham juntos para resultados reais.",
  "instagram_url": "http://instagram.com/omniforyou_",
  "og_image_url": "https://shpbvncguqczyohymjjx.supabase.co/storage/v1/object/public/site-images/1773106852847-278033733.jpg",
  "site_description": "Raquel Neumann é terapeuta especializada em fisioterapia pélvica e terapia sexual e performance íntima masculina.\n\nAtua há 18 anos, auxiliando homens a superarem disfunção erétil, ejaculação precoce e bloqueios emocionais relacionados à sexualidade.\n\nSeu trabalho une abordagem terapêutica estruturada, técnicas corporais e princípios do tantra, promovendo evolução gradual, controle e confiança.",
  "site_title": "Raquel Neumann - Terapeuta Sexual",
  "whatsapp_number": "5547996097029"
};
