-- 1. Create content table
CREATE TABLE IF NOT EXISTS content (
  key TEXT PRIMARY KEY,
  value TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create images table for gallery
CREATE TABLE IF NOT EXISTS images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  filename TEXT NOT NULL,
  url TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create product_categories table
CREATE TABLE IF NOT EXISTS product_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Create products table
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  long_description TEXT,
  price NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  image_url TEXT,
  category_id BIGINT REFERENCES product_categories(id) ON DELETE SET NULL,
  rating NUMERIC(2, 1) DEFAULT 5.0,
  reviews INTEGER DEFAULT 0,
  features JSONB DEFAULT '[]',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Create post_categories table
CREATE TABLE IF NOT EXISTS post_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Create posts table
CREATE TABLE IF NOT EXISTS posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  excerpt TEXT,
  content JSONB DEFAULT '[]',
  image_url TEXT,
  category_id BIGINT REFERENCES post_categories(id) ON DELETE SET NULL,
  published BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Create course_categories table
CREATE TABLE IF NOT EXISTS course_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Create courses table
CREATE TABLE IF NOT EXISTS courses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  instructor TEXT,
  price NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  image_url TEXT,
  category_id BIGINT REFERENCES course_categories(id) ON DELETE SET NULL,
  duration TEXT,
  lessons_count INTEGER DEFAULT 0,
  published BOOLEAN DEFAULT FALSE,
  allow_online_payment BOOLEAN DEFAULT TRUE,
  allow_partial_payment BOOLEAN DEFAULT FALSE,
  partial_payment_type TEXT CHECK (partial_payment_type IN ('fixed', 'percentage')) DEFAULT 'percentage',
  partial_payment_value NUMERIC(10, 2) DEFAULT 0.00,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
-- 9. Create customers table
CREATE TABLE IF NOT EXISTS customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  document TEXT,
  address_line1 TEXT,
  address_line2 TEXT,
  city TEXT,
  state TEXT,
  zip_code TEXT,
  status TEXT DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. Create orders table
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
  customer_name TEXT,
  customer_email TEXT,
  customer_phone TEXT,
  status TEXT CHECK (status IN ('pending', 'paid', 'processing', 'shipped', 'delivered', 'cancelled')) DEFAULT 'pending',
  total_amount NUMERIC(10, 2) DEFAULT 0.00,
  payment_method TEXT,
  payment_status TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. Create order_items table
CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
  course_id BIGINT REFERENCES courses(id) ON DELETE SET NULL,
  quantity INTEGER DEFAULT 1,
  unit_price NUMERIC(10, 2) DEFAULT 0.00,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 11. Create admin_users table
CREATE TABLE IF NOT EXISTS admin_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  name TEXT,
  role TEXT DEFAULT 'admin',
  status TEXT DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. Enable RLS (Row Level Security)
ALTER TABLE content ENABLE ROW LEVEL SECURITY;
ALTER TABLE images ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE post_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE course_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_users ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist to avoid errors
DROP POLICY IF EXISTS "Allow anon read content" ON content;
DROP POLICY IF EXISTS "Allow anon read images" ON images;
DROP POLICY IF EXISTS "Allow anon read categories" ON product_categories;
DROP POLICY IF EXISTS "Allow anon read products" ON products;
DROP POLICY IF EXISTS "Allow anon read post categories" ON post_categories;
DROP POLICY IF EXISTS "Allow anon read posts" ON posts;
DROP POLICY IF EXISTS "Allow anon read course categories" ON course_categories;
DROP POLICY IF EXISTS "Allow anon read courses" ON courses;
DROP POLICY IF EXISTS "Allow anon read customers" ON customers;
DROP POLICY IF EXISTS "Allow anon read orders" ON orders;
DROP POLICY IF EXISTS "Allow anon read order_items" ON order_items;
DROP POLICY IF EXISTS "Allow anon read admin_users" ON admin_users;

DROP POLICY IF EXISTS "Allow all for anon" ON content;
DROP POLICY IF EXISTS "Allow all for anon images" ON images;
DROP POLICY IF EXISTS "Allow all for anon categories" ON product_categories;
DROP POLICY IF EXISTS "Allow all for anon products" ON products;
DROP POLICY IF EXISTS "Allow all for anon post categories" ON post_categories;
DROP POLICY IF EXISTS "Allow all for anon posts" ON posts;
DROP POLICY IF EXISTS "Allow all for anon course categories" ON course_categories;
DROP POLICY IF EXISTS "Allow all for anon courses" ON courses;
DROP POLICY IF EXISTS "Allow all for anon customers" ON customers;
DROP POLICY IF EXISTS "Allow all for anon orders" ON orders;
DROP POLICY IF EXISTS "Allow all for anon order_items" ON order_items;
DROP POLICY IF EXISTS "Allow all for anon admin_users" ON admin_users;

-- Allow anonymous read access
CREATE POLICY "Allow anon read content" ON content FOR SELECT USING (true);
CREATE POLICY "Allow anon read images" ON images FOR SELECT USING (true);
CREATE POLICY "Allow anon read categories" ON product_categories FOR SELECT USING (true);
CREATE POLICY "Allow anon read products" ON products FOR SELECT USING (true);
CREATE POLICY "Allow anon read post categories" ON post_categories FOR SELECT USING (true);
CREATE POLICY "Allow anon read posts" ON posts FOR SELECT USING (true);
CREATE POLICY "Allow anon read course categories" ON course_categories FOR SELECT USING (true);
CREATE POLICY "Allow anon read courses" ON courses FOR SELECT USING (true);
CREATE POLICY "Allow anon read customers" ON customers FOR SELECT USING (true);
CREATE POLICY "Allow anon read orders" ON orders FOR SELECT USING (true);
CREATE POLICY "Allow anon read order_items" ON order_items FOR SELECT USING (true);
CREATE POLICY "Allow anon read admin_users" ON admin_users FOR SELECT USING (true);

-- Allow all (for simplicity in this prototype, usually restricted to 'authenticated' role)
CREATE POLICY "Allow all for anon" ON content FOR ALL USING (true);
CREATE POLICY "Allow all for anon images" ON images FOR ALL USING (true);
CREATE POLICY "Allow all for anon categories" ON product_categories FOR ALL USING (true);
CREATE POLICY "Allow all for anon products" ON products FOR ALL USING (true);
CREATE POLICY "Allow all for anon post categories" ON post_categories FOR ALL USING (true);
CREATE POLICY "Allow all for anon posts" ON posts FOR ALL USING (true);
CREATE POLICY "Allow all for anon course categories" ON course_categories FOR ALL USING (true);
CREATE POLICY "Allow all for anon courses" ON courses FOR ALL USING (true);
CREATE POLICY "Allow all for anon customers" ON customers FOR ALL USING (true);
CREATE POLICY "Allow all for anon orders" ON orders FOR ALL USING (true);
CREATE POLICY "Allow all for anon order_items" ON order_items FOR ALL USING (true);
CREATE POLICY "Allow all for anon admin_users" ON admin_users FOR ALL USING (true);


-- 8. Enable Storage
-- Make sure to create the 'site-images' bucket in the Supabase Dashboard and set it to PUBLIC.
-- If you want to do it via SQL (requires correct permissions):
INSERT INTO storage.buckets (id, name, public) 
VALUES ('site-images', 'site-images', true)
ON CONFLICT (id) DO NOTHING;

-- Storage Policies for 'site-images' bucket
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
DROP POLICY IF EXISTS "Anon Upload" ON storage.objects;
DROP POLICY IF EXISTS "Anon Update" ON storage.objects;
DROP POLICY IF EXISTS "Anon Delete" ON storage.objects;

CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING (bucket_id = 'site-images');
CREATE POLICY "Anon Upload" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'site-images');
CREATE POLICY "Anon Update" ON storage.objects FOR UPDATE USING (bucket_id = 'site-images');
CREATE POLICY "Anon Delete" ON storage.objects FOR DELETE USING (bucket_id = 'site-images');

-- 12. AI Auto Post Configurations
INSERT INTO content (key, value)
VALUES 
  ('autopost_enabled', 'false'),
  ('autopost_instructions', 'Você é a Raquel Neuman, uma especialista talentosa. Escreva posts atraentes sobre seus serviços de design, cursos e produtos. Use uma linguagem profissional porém acolhedora. Foque em como seus serviços ajudam pessoas e empresas a crescerem.'),
  ('autopost_days', '[]'),
  ('autopost_time', '09:00'),
  ('autopost_ai_provider', 'gemini'),
  ('autopost_last_run', NULL)
ON CONFLICT (key) DO NOTHING;

-- 13. Enable required extensions for Edge Functions and Scheduling
CREATE EXTENSION IF NOT EXISTS pg_cron;
CREATE EXTENSION IF NOT EXISTS pg_net;

-- 14. Schedule AI Auto Post (Runs every hour to check for scheduled posts)
-- IMPORTANT: Replace 'https://YOUR_PROJECT_ID.supabase.co' with your actual project URL
-- and 'YOUR_SERVICE_ROLE_KEY' with your service_role key.
/*
SELECT-- select cron.schedule('scheduled-blog-post', '0 * * * *', $$
--   select
--     net.http_post(
--       url:='https://YOUR_PROJECT_REF.supabase.co/functions/v1/blog-generator',
--       headers:=jsonb_build_object('Content-Type', 'application/json', 'Authorization', 'Bearer YOUR_SERVICE_ROLE_KEY'),
--       body:=jsonb_build_object('scheduled', true)
--     ) as request_id;
-- $$);
*/

-- ============================================================
-- MIGRATIONS (run these if you set up the DB before these columns were added)
-- ============================================================

-- Add category_id to posts (in case table was created without it)
ALTER TABLE posts ADD COLUMN IF NOT EXISTS category_id BIGINT REFERENCES post_categories(id) ON DELETE SET NULL;

-- Add external_link to products and courses
ALTER TABLE products ADD COLUMN IF NOT EXISTS external_link TEXT;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS external_link TEXT;
